#!/usr/bin/env python3
"""Fits Apple's device bezel PNGs to the website mockups.

Finds the transparent screen cutout in each bezel, writes a web-sized copy to
website/public/assets/bezels/, and writes website/public/bezels.css so the
`.dev-ipad` and `.dev-iphone` mockups sit exactly inside the screen with the
real frame drawn over them.

    python3 website/tools/fit_bezels.py --ipad "<landscape iPad>.png" --iphone "<portrait iPhone>.png"

Needs Pillow (pip3 install pillow).
"""
import argparse
from collections import deque
from pathlib import Path

from PIL import Image

PUBLIC = Path(__file__).resolve().parents[1] / 'public'
OUT_DIR = PUBLIC / 'assets' / 'bezels'
WEB_WIDTH = {'ipad': 1800, 'iphone': 900}


def screen_hole(img):
    """Bounding box and corner radius of the transparent area enclosed by the frame."""
    alpha = img.getchannel('A')
    w, h = img.size
    # Work on a reduced copy for the flood fill, then refine at full size.
    step = max(1, w // 600)
    sw, sh = w // step, h // step
    small = alpha.resize((sw, sh), Image.NEAREST).load()
    clear = lambda x, y: small[x, y] < 16
    outside = [[False] * sw for _ in range(sh)]
    q = deque()
    for x in range(sw):
        for y in (0, sh - 1):
            if clear(x, y) and not outside[y][x]:
                outside[y][x] = True; q.append((x, y))
    for y in range(sh):
        for x in (0, sw - 1):
            if clear(x, y) and not outside[y][x]:
                outside[y][x] = True; q.append((x, y))
    while q:
        x, y = q.popleft()
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            nx, ny = x + dx, y + dy
            if 0 <= nx < sw and 0 <= ny < sh and not outside[ny][nx] and clear(nx, ny):
                outside[ny][nx] = True; q.append((nx, ny))
    inside = [(x, y) for y in range(sh) for x in range(sw) if clear(x, y) and not outside[y][x]]
    if not inside:
        raise SystemExit('no transparent screen area found inside the frame')
    xs = [p[0] for p in inside]; ys = [p[1] for p in inside]
    # Refine each edge at full resolution, walking out from the hole's centre.
    full = alpha.load()
    cx = (min(xs) + max(xs) + 1) * step // 2
    cy = (min(ys) + max(ys) + 1) * step // 2
    is_clear = lambda x, y: full[x, y] < 16
    left = cx
    while left > 0 and is_clear(left - 1, cy): left -= 1
    right = cx
    while right < w - 1 and is_clear(right + 1, cy): right += 1
    top = cy
    while top > 0 and is_clear(cx, top - 1): top -= 1
    bottom = cy
    while bottom < h - 1 and is_clear(cx, bottom + 1): bottom += 1
    right += 1; bottom += 1

    # Corner radius: on the hole's top row the opening starts one radius in.
    start = cx
    while start > left and is_clear(start - 1, top): start -= 1
    radius = max(0, start - left)
    return left, top, right, bottom, radius


def fit(kind, path):
    img = Image.open(path).convert('RGBA')
    w, h = img.size
    left, top, right, bottom, radius = screen_hole(img)
    sw, sh = right - left, bottom - top
    web = img.resize((WEB_WIDTH[kind], round(h * WEB_WIDTH[kind] / w)), Image.LANCZOS)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    web.save(OUT_DIR / f'{kind}.png', optimize=True)
    pct = lambda v: f'{v * 100:.3f}%'
    print(f'{kind}: {w}x{h}, screen {sw}x{sh} at ({left},{top}), corner {radius}px')
    return f'''
.dev-{kind} {{ aspect-ratio: {w} / {h}; padding: {pct(top / w)} {pct((w - right) / w)} {pct((h - bottom) / w)} {pct(left / w)};
  background: none; box-shadow: none; border-radius: 0; }}
.dev-{kind}::after {{ content: ""; position: absolute; inset: 0; z-index: 6; pointer-events: none;
  background: url("assets/bezels/{kind}.png") center / 100% 100% no-repeat; }}
.dev-{kind} > .ui {{ border-radius: {pct(radius / sw)} / {pct(radius / sh)}; }}
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--ipad', help='landscape iPad bezel PNG')
    ap.add_argument('--iphone', help='portrait iPhone bezel PNG')
    args = ap.parse_args()
    css = '/* Generated by website/tools/fit_bezels.py from Apple Design Resources bezels. */\n'
    if args.ipad:
        css += fit('ipad', args.ipad)
    if args.iphone:
        css += fit('iphone', args.iphone)
        css += '.dev-iphone .island { display: none; } /* the bezel draws the Dynamic Island */\n'
    (PUBLIC / 'bezels.css').write_text(css)
    print(f'wrote {PUBLIC / "bezels.css"}')


if __name__ == '__main__':
    main()
